# Generated by Django 4.0 on 2022-01-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_delete_siteuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.OneToOneField(blank=True, default='default.jpg', on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
