# Generated by Django 4.0 on 2021-12-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
