# Generated by Django 4.0 on 2021-12-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_posts_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='head',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
